[package]
name = "zypher_verifier"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-lang = "0.29.0"

[lib]
name = "zypher_verifier"
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []